version: '3.8'
services:
  
  db:
     image: mysql
     ports: 
       - 3306:3306
     environment:
        MYSQL_ROOT_PASSWORD: root
     volumes:
      - ./sqls:/docker-entrypoint-initdb.d

  admin:
     image: adminer
     ports:
       - 8080:8080

  redis:
     image: redis
     ports:
       - 6379:6379
  rcli:
    image: redis
    links:
       - redis
    command: redis-cli -h redis
    command: >
       sh -c 'redis-cli -h redis '
    

  # redis-commander:
  #    container_name: redis-commander
  #    hostname: redis-commander
  #    image: rediscommander/redis-commander
  #    environment:
  #      - REDIS_HOSTS=local:redis:6379
  #    ports:
  #      - "8081:8081"