// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.19.1
// source: proto/botGetOrder.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BotOrderQueryRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	JWT string `protobuf:"bytes,1,opt,name=JWT,proto3" json:"JWT,omitempty"`
}

func (x *BotOrderQueryRequest) Reset() {
	*x = BotOrderQueryRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_botGetOrder_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BotOrderQueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BotOrderQueryRequest) ProtoMessage() {}

func (x *BotOrderQueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_botGetOrder_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BotOrderQueryRequest.ProtoReflect.Descriptor instead.
func (*BotOrderQueryRequest) Descriptor() ([]byte, []int) {
	return file_proto_botGetOrder_proto_rawDescGZIP(), []int{0}
}

func (x *BotOrderQueryRequest) GetJWT() string {
	if x != nil {
		return x.JWT
	}
	return ""
}

type BotOrderQueryResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OrderID    int32    `protobuf:"varint,1,opt,name=OrderID,proto3" json:"OrderID,omitempty"`
	TotalPrice int32    `protobuf:"varint,2,opt,name=TotalPrice,proto3" json:"TotalPrice,omitempty"`
	Finish     string   `protobuf:"bytes,3,opt,name=Finish,proto3" json:"Finish,omitempty"`
	Account    string   `protobuf:"bytes,4,opt,name=Account,proto3" json:"Account,omitempty"`
	Name       []string `protobuf:"bytes,5,rep,name=Name,proto3" json:"Name,omitempty"`
	Amount     []int64  `protobuf:"varint,6,rep,packed,name=Amount,proto3" json:"Amount,omitempty"`
	Price      []int64  `protobuf:"varint,7,rep,packed,name=Price,proto3" json:"Price,omitempty"`
}

func (x *BotOrderQueryResponse) Reset() {
	*x = BotOrderQueryResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_botGetOrder_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BotOrderQueryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BotOrderQueryResponse) ProtoMessage() {}

func (x *BotOrderQueryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_botGetOrder_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BotOrderQueryResponse.ProtoReflect.Descriptor instead.
func (*BotOrderQueryResponse) Descriptor() ([]byte, []int) {
	return file_proto_botGetOrder_proto_rawDescGZIP(), []int{1}
}

func (x *BotOrderQueryResponse) GetOrderID() int32 {
	if x != nil {
		return x.OrderID
	}
	return 0
}

func (x *BotOrderQueryResponse) GetTotalPrice() int32 {
	if x != nil {
		return x.TotalPrice
	}
	return 0
}

func (x *BotOrderQueryResponse) GetFinish() string {
	if x != nil {
		return x.Finish
	}
	return ""
}

func (x *BotOrderQueryResponse) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *BotOrderQueryResponse) GetName() []string {
	if x != nil {
		return x.Name
	}
	return nil
}

func (x *BotOrderQueryResponse) GetAmount() []int64 {
	if x != nil {
		return x.Amount
	}
	return nil
}

func (x *BotOrderQueryResponse) GetPrice() []int64 {
	if x != nil {
		return x.Price
	}
	return nil
}

type BotOrderCreateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ItemID     []int64 `protobuf:"varint,1,rep,packed,name=ItemID,proto3" json:"ItemID,omitempty"`
	Amount     []int64 `protobuf:"varint,2,rep,packed,name=Amount,proto3" json:"Amount,omitempty"`
	Price      []int64 `protobuf:"varint,3,rep,packed,name=Price,proto3" json:"Price,omitempty"`
	JWT        string  `protobuf:"bytes,4,opt,name=JWT,proto3" json:"JWT,omitempty"`
	TotalPrice int32   `protobuf:"varint,5,opt,name=TotalPrice,proto3" json:"TotalPrice,omitempty"`
	ID         []int64 `protobuf:"varint,6,rep,packed,name=ID,proto3" json:"ID,omitempty"`
}

func (x *BotOrderCreateRequest) Reset() {
	*x = BotOrderCreateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_botGetOrder_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BotOrderCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BotOrderCreateRequest) ProtoMessage() {}

func (x *BotOrderCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_botGetOrder_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BotOrderCreateRequest.ProtoReflect.Descriptor instead.
func (*BotOrderCreateRequest) Descriptor() ([]byte, []int) {
	return file_proto_botGetOrder_proto_rawDescGZIP(), []int{2}
}

func (x *BotOrderCreateRequest) GetItemID() []int64 {
	if x != nil {
		return x.ItemID
	}
	return nil
}

func (x *BotOrderCreateRequest) GetAmount() []int64 {
	if x != nil {
		return x.Amount
	}
	return nil
}

func (x *BotOrderCreateRequest) GetPrice() []int64 {
	if x != nil {
		return x.Price
	}
	return nil
}

func (x *BotOrderCreateRequest) GetJWT() string {
	if x != nil {
		return x.JWT
	}
	return ""
}

func (x *BotOrderCreateRequest) GetTotalPrice() int32 {
	if x != nil {
		return x.TotalPrice
	}
	return 0
}

func (x *BotOrderCreateRequest) GetID() []int64 {
	if x != nil {
		return x.ID
	}
	return nil
}

type BotOrderCreateResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *BotOrderCreateResponse) Reset() {
	*x = BotOrderCreateResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_botGetOrder_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BotOrderCreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BotOrderCreateResponse) ProtoMessage() {}

func (x *BotOrderCreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_botGetOrder_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BotOrderCreateResponse.ProtoReflect.Descriptor instead.
func (*BotOrderCreateResponse) Descriptor() ([]byte, []int) {
	return file_proto_botGetOrder_proto_rawDescGZIP(), []int{3}
}

type BotOrderUpdateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ItemID     []int64 `protobuf:"varint,1,rep,packed,name=ItemID,proto3" json:"ItemID,omitempty"`
	Amount     []int64 `protobuf:"varint,2,rep,packed,name=Amount,proto3" json:"Amount,omitempty"`
	Price      []int64 `protobuf:"varint,3,rep,packed,name=Price,proto3" json:"Price,omitempty"`
	JWT        string  `protobuf:"bytes,4,opt,name=JWT,proto3" json:"JWT,omitempty"`
	TotalPrice int32   `protobuf:"varint,5,opt,name=TotalPrice,proto3" json:"TotalPrice,omitempty"`
	ID         []int64 `protobuf:"varint,6,rep,packed,name=ID,proto3" json:"ID,omitempty"`
}

func (x *BotOrderUpdateRequest) Reset() {
	*x = BotOrderUpdateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_botGetOrder_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BotOrderUpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BotOrderUpdateRequest) ProtoMessage() {}

func (x *BotOrderUpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_botGetOrder_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BotOrderUpdateRequest.ProtoReflect.Descriptor instead.
func (*BotOrderUpdateRequest) Descriptor() ([]byte, []int) {
	return file_proto_botGetOrder_proto_rawDescGZIP(), []int{4}
}

func (x *BotOrderUpdateRequest) GetItemID() []int64 {
	if x != nil {
		return x.ItemID
	}
	return nil
}

func (x *BotOrderUpdateRequest) GetAmount() []int64 {
	if x != nil {
		return x.Amount
	}
	return nil
}

func (x *BotOrderUpdateRequest) GetPrice() []int64 {
	if x != nil {
		return x.Price
	}
	return nil
}

func (x *BotOrderUpdateRequest) GetJWT() string {
	if x != nil {
		return x.JWT
	}
	return ""
}

func (x *BotOrderUpdateRequest) GetTotalPrice() int32 {
	if x != nil {
		return x.TotalPrice
	}
	return 0
}

func (x *BotOrderUpdateRequest) GetID() []int64 {
	if x != nil {
		return x.ID
	}
	return nil
}

type BotOrderUpdateResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *BotOrderUpdateResponse) Reset() {
	*x = BotOrderUpdateResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_botGetOrder_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BotOrderUpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BotOrderUpdateResponse) ProtoMessage() {}

func (x *BotOrderUpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_botGetOrder_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BotOrderUpdateResponse.ProtoReflect.Descriptor instead.
func (*BotOrderUpdateResponse) Descriptor() ([]byte, []int) {
	return file_proto_botGetOrder_proto_rawDescGZIP(), []int{5}
}

var File_proto_botGetOrder_proto protoreflect.FileDescriptor

var file_proto_botGetOrder_proto_rawDesc = []byte{
	0x0a, 0x17, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x62, 0x6f, 0x74, 0x47, 0x65, 0x74, 0x4f, 0x72,
	0x64, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x22, 0x28, 0x0a, 0x14, 0x42, 0x6f, 0x74, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x51,
	0x75, 0x65, 0x72, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x4a,
	0x57, 0x54, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x4a, 0x57, 0x54, 0x22, 0xc5, 0x01,
	0x0a, 0x15, 0x42, 0x6f, 0x74, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x51, 0x75, 0x65, 0x72, 0x79, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x4f, 0x72, 0x64, 0x65, 0x72,
	0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x49,
	0x44, 0x12, 0x1e, 0x0a, 0x0a, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x50, 0x72, 0x69, 0x63, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x50, 0x72, 0x69, 0x63,
	0x65, 0x12, 0x16, 0x0a, 0x06, 0x46, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x46, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x12, 0x18, 0x0a, 0x07, 0x41, 0x63, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x41, 0x63, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x03, 0x28,
	0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x41, 0x6d, 0x6f, 0x75, 0x6e,
	0x74, 0x18, 0x06, 0x20, 0x03, 0x28, 0x03, 0x52, 0x06, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12,
	0x14, 0x0a, 0x05, 0x50, 0x72, 0x69, 0x63, 0x65, 0x18, 0x07, 0x20, 0x03, 0x28, 0x03, 0x52, 0x05,
	0x50, 0x72, 0x69, 0x63, 0x65, 0x22, 0x9f, 0x01, 0x0a, 0x15, 0x42, 0x6f, 0x74, 0x4f, 0x72, 0x64,
	0x65, 0x72, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x16, 0x0a, 0x06, 0x49, 0x74, 0x65, 0x6d, 0x49, 0x44, 0x18, 0x01, 0x20, 0x03, 0x28, 0x03, 0x52,
	0x06, 0x49, 0x74, 0x65, 0x6d, 0x49, 0x44, 0x12, 0x16, 0x0a, 0x06, 0x41, 0x6d, 0x6f, 0x75, 0x6e,
	0x74, 0x18, 0x02, 0x20, 0x03, 0x28, 0x03, 0x52, 0x06, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12,
	0x14, 0x0a, 0x05, 0x50, 0x72, 0x69, 0x63, 0x65, 0x18, 0x03, 0x20, 0x03, 0x28, 0x03, 0x52, 0x05,
	0x50, 0x72, 0x69, 0x63, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x4a, 0x57, 0x54, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x4a, 0x57, 0x54, 0x12, 0x1e, 0x0a, 0x0a, 0x54, 0x6f, 0x74, 0x61, 0x6c,
	0x50, 0x72, 0x69, 0x63, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x54, 0x6f, 0x74,
	0x61, 0x6c, 0x50, 0x72, 0x69, 0x63, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x06, 0x20,
	0x03, 0x28, 0x03, 0x52, 0x02, 0x49, 0x44, 0x22, 0x18, 0x0a, 0x16, 0x42, 0x6f, 0x74, 0x4f, 0x72,
	0x64, 0x65, 0x72, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x9f, 0x01, 0x0a, 0x15, 0x42, 0x6f, 0x74, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x49,
	0x74, 0x65, 0x6d, 0x49, 0x44, 0x18, 0x01, 0x20, 0x03, 0x28, 0x03, 0x52, 0x06, 0x49, 0x74, 0x65,
	0x6d, 0x49, 0x44, 0x12, 0x16, 0x0a, 0x06, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20,
	0x03, 0x28, 0x03, 0x52, 0x06, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x50,
	0x72, 0x69, 0x63, 0x65, 0x18, 0x03, 0x20, 0x03, 0x28, 0x03, 0x52, 0x05, 0x50, 0x72, 0x69, 0x63,
	0x65, 0x12, 0x10, 0x0a, 0x03, 0x4a, 0x57, 0x54, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x4a, 0x57, 0x54, 0x12, 0x1e, 0x0a, 0x0a, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x50, 0x72, 0x69, 0x63,
	0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x50, 0x72,
	0x69, 0x63, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x06, 0x20, 0x03, 0x28, 0x03, 0x52,
	0x02, 0x49, 0x44, 0x22, 0x18, 0x0a, 0x16, 0x42, 0x6f, 0x74, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32, 0x8f, 0x02,
	0x0a, 0x0b, 0x42, 0x6f, 0x74, 0x47, 0x65, 0x74, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x12, 0x52, 0x0a,
	0x0d, 0x42, 0x6f, 0x74, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x51, 0x75, 0x65, 0x72, 0x79, 0x12, 0x1e,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x42, 0x6f, 0x74, 0x4f, 0x72, 0x64,
	0x65, 0x72, 0x51, 0x75, 0x65, 0x72, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x42, 0x6f, 0x74, 0x4f, 0x72, 0x64,
	0x65, 0x72, 0x51, 0x75, 0x65, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x00, 0x12, 0x55, 0x0a, 0x0e, 0x42, 0x6f, 0x74, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x12, 0x1f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x42,
	0x6f, 0x74, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e,
	0x42, 0x6f, 0x74, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x55, 0x0a, 0x0e, 0x42, 0x6f, 0x74, 0x4f,
	0x72, 0x64, 0x65, 0x72, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x12, 0x1f, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x42, 0x6f, 0x74, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x42, 0x6f, 0x74, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42,
	0x0c, 0x5a, 0x0a, 0x2e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_botGetOrder_proto_rawDescOnce sync.Once
	file_proto_botGetOrder_proto_rawDescData = file_proto_botGetOrder_proto_rawDesc
)

func file_proto_botGetOrder_proto_rawDescGZIP() []byte {
	file_proto_botGetOrder_proto_rawDescOnce.Do(func() {
		file_proto_botGetOrder_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_botGetOrder_proto_rawDescData)
	})
	return file_proto_botGetOrder_proto_rawDescData
}

var file_proto_botGetOrder_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_botGetOrder_proto_goTypes = []interface{}{
	(*BotOrderQueryRequest)(nil),   // 0: protobuf.BotOrderQueryRequest
	(*BotOrderQueryResponse)(nil),  // 1: protobuf.BotOrderQueryResponse
	(*BotOrderCreateRequest)(nil),  // 2: protobuf.BotOrderCreateRequest
	(*BotOrderCreateResponse)(nil), // 3: protobuf.BotOrderCreateResponse
	(*BotOrderUpdateRequest)(nil),  // 4: protobuf.BotOrderUpdateRequest
	(*BotOrderUpdateResponse)(nil), // 5: protobuf.BotOrderUpdateResponse
}
var file_proto_botGetOrder_proto_depIdxs = []int32{
	0, // 0: protobuf.BotGetOrder.BotOrderQuery:input_type -> protobuf.BotOrderQueryRequest
	2, // 1: protobuf.BotGetOrder.BotOrderCreate:input_type -> protobuf.BotOrderCreateRequest
	4, // 2: protobuf.BotGetOrder.BotOrderUpdate:input_type -> protobuf.BotOrderUpdateRequest
	1, // 3: protobuf.BotGetOrder.BotOrderQuery:output_type -> protobuf.BotOrderQueryResponse
	3, // 4: protobuf.BotGetOrder.BotOrderCreate:output_type -> protobuf.BotOrderCreateResponse
	5, // 5: protobuf.BotGetOrder.BotOrderUpdate:output_type -> protobuf.BotOrderUpdateResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_botGetOrder_proto_init() }
func file_proto_botGetOrder_proto_init() {
	if File_proto_botGetOrder_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_botGetOrder_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BotOrderQueryRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_botGetOrder_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BotOrderQueryResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_botGetOrder_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BotOrderCreateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_botGetOrder_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BotOrderCreateResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_botGetOrder_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BotOrderUpdateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_botGetOrder_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BotOrderUpdateResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_botGetOrder_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_botGetOrder_proto_goTypes,
		DependencyIndexes: file_proto_botGetOrder_proto_depIdxs,
		MessageInfos:      file_proto_botGetOrder_proto_msgTypes,
	}.Build()
	File_proto_botGetOrder_proto = out.File
	file_proto_botGetOrder_proto_rawDesc = nil
	file_proto_botGetOrder_proto_goTypes = nil
	file_proto_botGetOrder_proto_depIdxs = nil
}
